GET localhost:8888/api/routes

###-------------------------
GET localhost:8888/api/routes/XXXX

###----------------------------
POST localhost:8888/api/routes
content-type: application/json
Authorization: XXXXXX

{
  "name": "Nueva ruta",
  "duration": "2h 10 min",
  "difficult": "Super easy",
  "unit": "KM",
  "description": "No hay cuestas, un falso llano :>",
  "distance": 18
}

###-------------------------------
PUT localhost:8888/api/routes/XXXX
content-type: application/json
Authorization: XXXXXX

{
  "name": "Hola",
  "duration": "2h 10 min",
  "difficult": "Super easy",
  "unit": "KM",
  "description": "No hay cuestas, un falso llano :>",
  "distance": 18
}

###-------------------------------
DELETE localhost:8888/api/routes/XXXX
Authorization: XXXXXX
