POST http://localhost:8888/api/auth/login
content-type: application/json

{
  "email": "baldo@mero.com",
  "password": "123456789"
}

###--------------------------------------- register
POST http://localhost:8888/api/auth/register
content-type: application/json

{
  "email": "baldo@mero.com",
  "password": "123456789",
  "name": "Baldomero Andate ligero"
}

###---------------------------------- get user
GET http://localhost:8888/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTFjZjcwYjY4ZjUwMDBiMzAzNzY1MiIsIm5hbWUiOiJCYWxkb21lcm8gQW5kYXRlIGxpZ2VybyIsImVtYWlsIjoiYmFsZG9AbWVyby5jb20iLCJpYXQiOjE2MjU0MTE0NDAsImV4cCI6MTYyNjAxNjI0MH0.7uNe8GGZTS3SyDQRxcCvg27eNE8FzYF_Hd4XfaSz5k8

### ------

DELETE http://localhost:8888/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTFjZjcwYjY4ZjUwMDBiMzAzNzY1MiIsIm5hbWUiOiJCYWxkb21lcm8gQW5kYXRlIGxpZ2VybyIsImVtYWlsIjoiYmFsZG9AbWVyby5jb20iLCJpYXQiOjE2MjU0MTE0NDAsImV4cCI6MTYyNjAxNjI0MH0.7uNe8GGZTS3SyDQRxcCvg27eNE8FzYF_Hd4XfaSz5k8