POST http://localhost:8888/api/auth/login
content-type: application/json

{
  "email": "baldo@mero.com",
  "password": "123456789"
}

###--------------------------------------- register
POST http://localhost:8888/api/auth/register
content-type: application/json

{
  "email": "baldo@mero.com",
  "password": "123456789",
  "name": "Baldomero Andate ligero"
}

###---------------------------------- get user
GET http://localhost:8888/api/user
Authorization: XXXXXX
### ------

DELETE http://localhost:8888/api/user
Authorization: XXXXXX